name: Assign PR

on:
  pull_request:
    types:
      - opened

jobs:
  assign-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assign PR creator
        uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
