/* 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/293261 */

-- FISH_INFO : ID, FISH_TYPE, LENGTH, TIME
-- FISH_NAME_INFO : FISH_TYPE, FISH_NAME

-- 방법 1
SELECT FI.ID, FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
         JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = FI.FISH_TYPE
)
ORDER BY FI.ID;


-- 방법 2 : 튜플(ROW CONSTRUCTOR) 비교
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
         JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH)
          IN (
              SELECT FISH_TYPE, MAX(LENGTH)
              FROM FISH_INFO
              GROUP BY FISH_TYPE
          )
ORDER BY FI.ID;